database:
  driverClass: com.mysql.jdbc.Driver
  user: bfcb065791f55b
  password: db7700da
  url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/heroku_caa48378bf4cc5b
logging:
  loggers:
    "com.sun.jersey.api.container.filter.LoggingFilter": INFO
    "org.eclipse.jetty.servlets": DEBUG
    "org.glassfish.jersey.filter.LoggingFilter": DEBUG
# Extending from the default server configuration
server:
  applicationConnectors:
    - type: http
      port: 1337
      bindHost: 127.0.0.1 # only bind to loopback
      headerCacheSize: 512 bytes
      outputBufferSize: 32KiB
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      inputBufferSize: 8KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
      soLingerTime: 345s
      useServerHeader: false
      useDateHeader: true
      useForwardedHeaders: true
  adminConnectors:
    - type: http
      port: 1338
      bindHost: 127.0.0.1 # only bind to loopback
      headerCacheSize: 512 bytes
      outputBufferSize: 32KiB
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      inputBufferSize: 8KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
      soLingerTime: 345s
      useServerHeader: false
      useDateHeader: true
      useForwardedHeaders: true